# Generated by Django 3.2.5 on 2022-07-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction_listings',
            new_name='auction_listing',
        ),
    ]
