# Generated by Django 3.2.5 on 2022-07-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_auction_listings_bid_auction_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='new_bid',
            field=models.IntegerField(),
        ),
    ]
