# Generated by Django 3.2.5 on 2022-07-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_new_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='starting_bid',
            new_name='price',
        ),
    ]
