# Generated by Django 3.2.5 on 2022-07-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_starting_bid_auctionlistings_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
