# Generated by Django 3.2.5 on 2022-08-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_transactionreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreference',
            name='bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
            preserve_default=False,
        ),
    ]
