# Generated by Django 3.2.5 on 2022-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20220811_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='trx_ref',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
